#!/bin/sh
#Reglas comentadas son las recomendadas si se quiere tener un política restrictiva
#iptables -P INPUT DROP
#iptables -P FORWARD DROP
#iptables -F INPUT
#iptables -Z INPUT
#iptables -F FORWARD
#iptables -Z FORWARD
#iptables -I FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
#iptables -I FORWARD -j TESISBLOQUOES
#iptables -I INPUT -i lo -j ACCEPT
#iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -N MATFEL
iptables -A FORWARD -j MATFEL
