#!/bin/sh
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -F INPUT
iptables -Z INPUT
iptables -F FORWARD
iptables -Z FORWARD
iptables -N TESIS
iptables -A FORWARD -j TESIS
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -I INPUT -i lo -j ACCEPT
iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -I INPUT -p tcp --dport 22 -j ACCEPT
iptables -I INPUT -p tcp --dport 3000 -j ACCEPT
