package MatFel::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MatFel::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:tesis',
        user => 'tesis',
        password => 'test',
    }
);

=head1 NAME

MatFel::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MatFel>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MatFel::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

soporte

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
