#!/bin/bash 


###############
## Funciones ##
###############
function setearCron(){
echo "#Actualizacion del archivo de configuracion de openVAS" >> /etc/crontab
echo "0 0 * * * openvas-nvt-sync&  > /dev/null 2>&1" >> /etc/crontab
echo "5 0 * * * /etc/init.d/openvas-scanner restart&  > /dev/null 2>&1" >> /etc/crontab
}
function instalarOpenVAS(){
    echo "Tener en cuenta que este paso puede tener inconventientes ya que el openvas va cambiando al igual q las versiones disponibles para Debian"    
    read -p "AVISO!!! Se instalarán las dependencias de Openvas desde repos de ellos y el nikto que esta en la sección non-free de los repos de debian" ESPERA
    #########################
    ##Montar el repositorio##
    #########################
    echo "deb http://download.opensuse.org/repositories/security:/OpenVAS:/UNSTABLE:/v6/Debian_7.0/ ./" >> /etc/apt/sources.list
	wget http://download.opensuse.org/repositories/security:/OpenVAS:/UNSTABLE:/v6/Debian_7.0/Release.key
	apt-key add ./Release.key
	apt-get update
    ######################
    ## Instalar OpenVas ##
    ######################
    apt-get -y install greenbone-security-assistant openvas-cli openvas-manager openvas-scanner openvas-administrator sqlite3 xsltproc rsync 
    read -p "AVISO!!! Los siguiente sólo funcionará si están los non-free, sino ignore el error" ESPERA
    apt-get -y install nikto
	#############################
    ## Instalar OpenVas Extras ##
    #############################
    #Deshabilitado por ahora
	#To install support packages for report generation (downloads around 30 MB of additional packages):
    #apt-get -y install texlive-latex-base texlive-latex-extra texlive-latex-recommended htmldoc
	#To install support for autogenerated LSC credential packages:
	#apt-get -y install alien rpm nsis fakeroot
		
	########################
    ## Configurar OpenVas ##
    ########################
	#Crear certificado del servidor
    test -e /var/lib/openvas/CA/cacert.pem  || openvas-mkcert -q
	#Bajar los plugins
    read -p "AVISO!!! Se actualizarán los plugins de openvas, esto puede demorar un buen rato (Presione Enter para continuar)" ESPERA
    openvas-nvt-sync
	#Agregar un usuario
    test -e /var/lib/openvas/users/om || openvas-mkcert-client -n om -i
	/etc/init.d/openvas-manager stop
	/etc/init.d/openvas-scanner stop
	#Voy a reconstruir el servidor
	read -p "AVISO!!! Se reconstruiran los archivos del servidor, esto casi seguro puede demorar un buen rato (Presione Enter para continuar)" ESPERA
	cp -a $LUGAR/docs/instalador/auxiliaresOpenVas/cert /usr/share/openvas/
    openvassd
	openvasmd --rebuild
	openvas-scapdata-sync
	openvas-certdata-sync
	
	read -p "AVISO!!! Se creara el usuario que usará el openvas con rol de administrador (Ingreselo, por defecto será matfel)" OPENVASUSER
	if [ -z $OPENVASUSER ]
	then
		OPENVASUSER="matfel"
	fi
    test -e /var/lib/openvas/users/admin || openvasad -c add_user -n $OPENVASUSER -r Admin
	
	echo "Reiniciando Openvas y todos sus componente"
	killall openvassd
	sleep 15
	/etc/init.d/openvas-scanner start
	/etc/init.d/openvas-manager start
	/etc/init.d/openvas-administrator restart
	/etc/init.d/greenbone-security-assistant restart
		
    #Nikto - a web server scanning and testing tool
    nikto -update
    #instalarWapiti
    #echo "Tuve que hacer un parche para que el Openvasd encienda por defecto en la maquina donde esta instalado y reinstalar los scripts de inicio en los runlevels 1, 2, 3, y 4"
    #cp $LUGAR/docs/instalador/aux/openvas-scanner /etc/init.d/
    #update-rc.d -f openvas-scanner remove
    #update-rc.d openvas-scanner defaults
}


function instalarWapiti(){
    #Wapiti - Web application vulnerability scanner / security auditor --> 2
    echo "Procesando Wapiti"
    cd $LUGAR/script
    wget http://ufpr.dl.sourceforge.net/project/wapiti/wapiti/wapiti-2.2.1/wapiti-2.2.1.tar.bz2
    tar xjvf wapiti-2.2.1.tar.bz2
    
    #Crear un script /usr/bin/wapiti
    echo '#!/bin/sh' > /usr/bin/wapiti
    echo "cd $LUGAR/script/wapiti-2.2.1/src/" >> /usr/bin/wapiti
    echo 'python wapiti.py $*' >> /usr/bin/wapiti
    chmod +x /usr/bin/wapiti
}


LUGAR=$1
instalarOpenVAS
setearCron

##Bugs conocidos, revisar si openvas-cli es necesario en una arquitectura distribuida
##El script de inicio de openvas-scanner no anda....hay que modificarlo
